version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "5051:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_CERTIFICATE_PASSWORD=${ASPNETCORE_CERTIFICATE_PASSWORD}
      - JwtSettings__Authority=https://localhost:5052
      - Proxies__KnownProxies=${Proxies__KnownProxies}
    depends_on:
      - identityserver
    volumes:
      - ~/.aspnet/https:/https:ro
      
  identityserver:
    build:
      context: .
      dockerfile: identityserver/Dockerfile
    container_name: identityserver
    ports:
      - "5052:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_CERTIFICATE_PASSWORD=${ASPNETCORE_CERTIFICATE_PASSWORD}
      - Proxies__KnownProxies=${Proxies__KnownProxies}
    volumes:
      - ~/.aspnet/https:/https:ro
      - keys:/home/app/.aspnet/DataProtection-Keys
      
volumes:
  keys: