import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import LeftNav from "@/components/overview/left-nav";
import React from "react";
import {getSession} from "../../auth";
import NextAuthProviders from "@/providers/nextauth-provider";
import {Toaster} from "@/components/ui/toaster";
import {ReactQueryProvider} from "@/providers/reactquery-provider";
import {NextThemeProvider} from "@/providers/nexttheme-provider";

const roboto = Roboto({
    weight: ["100", "300", "400", "500", "700", "900"],
    style: ["normal", "italic"],
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    const session = await getSession();

    return (
        <html lang="en" className={`${roboto.className}`} suppressHydrationWarning>
            <body>
                <NextThemeProvider>
                    <NextAuthProviders session={session}>
                        <ReactQueryProvider>
                            <main className="flex">
                                <LeftNav/>
                                <div className="bg-white text-black flex-1">
                                    {children}
                                </div>
                                <Toaster/>
                            </main>
                        </ReactQueryProvider>
                    </NextAuthProviders>
                </NextThemeProvider>
            </body>
        </html>
    );
}
